### ISSUE TITLE
aws-sdk version requirement is not high enough to support ECR

### ISSUE THREAD

**Issue by jzhu9** [DispatchBot/node-ecs-deployer#6]
The ecr deployment type uses the `describeImages()` function, which isn't available until version [2.6.8](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#268), but the aws-sdk minimum requirement is only [2.1.50](https://github.com/DispatchBot/node-ecs-deployer/blob/master/package.json#L16).

If an existing project already has an older version of node-ecs-deployer listed in the package.json with a base aws-sdk requirement less than 2.6.8, when the node-ecs-deployer version is bumped up to 0.6.0 to use the ECR deploy, the aws-sdk version is not updated to a version that supports the `describeImages()` function and deploys will fail.

**Comment by bradseefeld** [comment]
Fixed in version 0.6.1
